name: BuildPfExampleSketch
on: 
  push:
    paths: 
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '.github/workflows/*.yml'
  pull_request:
    paths: 
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '.github/workflows/*.yml'

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        arduino-boards-fqbn:
          - esp32:esp32:pico32
          - esp32:esp32:heltec_wifi_kit_32
          - esp32:esp32:esp32wrover
          - esp8266:esp8266:nodemcuv2
          - esp8266:esp8266:d1 
          - esp8266:esp8266:huzzah
          - arduino:avr:uno
          - arduino:avr:nano:cpu=atmega328      

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile only power function example for different platforms
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
        sketch-names: "PowerFunctions.ino"
        platform-url: https://dl.espressif.com/dl/package_esp32_index.json,https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: NimBLE-Arduino # use latest version
